### PR TITLE
Add components to dasherisation exception

### PR DESCRIPTION
**Pull request by backspace**
This is a proposed fix for emberjs/ember.js#18215. I’m definitely unfamiliar with this code but the approach was [suggested by @rwjblue](https://github.com/emberjs/ember.js/issues/18215#issuecomment-513999905), hopefully this is a correct implementation!

### CODE REVIEW

**Comment by rwjblue** [comment]
Will try to merge and release tomorrow. Thanks for working on this!

**Comment by backspace** [comment]
You’re welcome, happy to help, thanks for the guidance!

**Comment by Turbo87** [comment]
unfortunately, this change is breaking quite a few of our apps. we use something like this:

```hbs
  {{#power-select
    beforeOptionsComponent="x-select.search-message"
    ...
  }}
```

and with this new release we get:

> Could not find component named "x-select.search-message" (no component or template with that name was found)

not sure what to do about this. are we doing it wrong? should this be re-released as a breaking change with a major version bump? 🤔

**Comment by backspace** [comment]
oh noooo maybe the version should be pulled? 😳

**Comment by rwjblue** [comment]
@Turbo87 - What is `x-select.search-message` in your app? I'm trying to actually understand the failure mode here...

**Comment by rwjblue** [comment]
> should this be re-released as a breaking change with a major version bump? 🤔

Seems generally fine, but I want to grok the issue better first

**Comment by dcyriller** [comment]
> @Turbo87 - What is x-select.search-message in your app? I'm trying to actually understand the failure mode here...

`x-select.search-message` is a component defined in: `addon/components/x-select/search-message.js`. It aims at being used with power-select to override a default component.

**Comment by dcyriller** [comment]
Renaming the componentName from `x-select.search-message` to `x-select/search-message` actually fixes the issue.

For reference, here is power-select code that consumes [the component name](https://github.com/cibernox/ember-power-select/blob/cfa45a31f4a91abb969128be5b14e4776e308cd6/addon/templates/components/power-select.hbs#L54).

I would have not expected `x-select.search-message` to work in the first place... Don't know if it was something expected.

**Comment by rwjblue** [comment]
> I would have not expected x-select.search-message to work in the first place...

Totally agree! I am also surprised by this.

**Comment by rwjblue** [comment]
I recall a similar issue way back in Ember 2.10 (https://github.com/emberjs/ember.js/issues/14659 for those interested in reading through it), and we also agreed that using `.` for folder separation was undefined (and therefore not a "breaking change"). I don't expect this to bite many folks (2.10 already forbade `{{folder-name.comp-name}}` so we are only talking about `{{component 'folder-name.comp-name'}}` which is an even narrower case), and I'd prefer to keep this change essentially as a bugfix (since it does help folks in the larger case of ambiguous local paths being invoked as components in Ember 3.10+).

**Pull request merged**
