### PR TITLE
Improve performance of translateToContainerFullname function

### PR DESCRIPTION
**Pull request by joshvfleming**
While CPU profiling our app, we noticed that the
translateToContainerFullname function was taking quite a lot of time,
and this seemed to be mostly on account of regex use. This commit replaces
the regexes with equivalent string manipulation logic. The
translateToContainerFullname disappeared from the offenders list in our
CPU profiles after the change.

Before:

translatetocontainerfullname-fix-before

After:

translatetocontainerfullname-fix-after

### CODE REVIEW

**Comment by stefanpenner** [comment]
@joshvfleming good catch. I guess ED was having some fun translating :P

**Comment by stefanpenner** [comment]
@joshvfleming looks like some failing tests yet, otherwise it appears like a great addition.

**Comment by rwjblue** [comment]
Looks like failing tests have to do with bad setup (returning something as a route that isn't stamped with `isRouteFactory`) and changes on Ember canary.

**Comment by stefanpenner** [comment]
@joshvfleming also curious:

* which version of ember
* which version of data
* is this a prod build

**Comment by stefanpenner** [comment]
actually a quick look, indicates we likely really shouldn't be calling this method that many times.

https://github.com/ember-cli/ember-resolver/blob/604c12d0b2b05ea2b5e4c6a8a16e32a8cf8e56ef/packages/ember-resolver/lib/core.js#L344

Although it is great to make it faster,  calling it so many times is potentially related to a large underlying issue.

**Comment by rwjblue** [comment]
`knownForType` should be called once for initial render of each test.

**Comment by joshvfleming** [comment]
Ember canary 987a593 (I don't see this on the commit list anymore, but it's around a week old)
Ember-data canary 9a85784
Prod build
Another potentially relevant data point: this is running in fastboot mode in Node, v 0.12.7

This is the stack I'm seeing:

screen shot 2015-08-28 at 5 32 29 pm

It does seem to be one really slow call rather than an aggregation of a large number calls.

Also, I believe the test failures are unrelated to this commit -- the tests fail the same way for me with the previous commit.

**Comment by stefanpenner** [comment]
> Also, I believe the test failures are unrelated to this commit -- the tests fail the same way for me with the previous commit.

ya, @rwjblue mentioned it was an issue with latest canary.



> It does seem to be a small number of really slow calls rather than an aggregation of a large number calls.

interesting, so this must mean a large number of internal modules (thousands)

**Comment by stefanpenner** [comment]
@rwjblue you seem to have a clear grasp on the test failure. Do you have time to look, or share the steps?

I would love to release a new version of the resolver shortly including @joshvfleming's work.

**Comment by stefanpenner** [comment]
@rwjblue another approach, to mitigate the need for this at all. Is to do this at compilation time, and providing some module meta-data pre-constructed.

**Comment by rwjblue** [comment]
Ya, I will PR fixing the test failure to master so we can focus on this separately.

**Comment by stefanpenner** [comment]
> Ya, I will PR fixing the test failure to master so we can focus on this separately.
>  Hide all checks

thanks

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-resolver/pull/112 should fix master

**Comment by stefanpenner** [comment]
@joshvfleming can we get a quick rebase

**Comment by joshvfleming** [comment]
@stefanpenner Just rebased and pushed. Regarding the call counts, I'll need to grab that from my work laptop on Monday.

Thanks @stefanpenner and @rwjblue for looking into this so quickly!

**Comment by stefanpenner** [comment]
release as v0.1.21

**Comment by rwjblue** [comment]
Thanks!

**Pull request merged**
