### PR TITLE
Add podModulePrefix deprecation warning.

### PR DESCRIPTION
**Pull request by trabus**
This PR adds a deprecation warning when 'podModulePrefix' is defined on the resolver.

### CODE REVIEW

**Comment by rwjblue** [comment]
Added a few commits fixing up the error that you were having.  This is good to go now.

**Comment by rwjblue** [comment]
Tagged as v0.1.13.

**Comment by rwjblue** [comment]
A few changes made in https://github.com/ember-cli/ember-resolver/pull/89 (had to make the deprecation lazy because of silly ember-cli blueprint).

**Comment by trabus** [comment]
@rwjblue Thanks for tracking that down, and fixing it. I wasn't getting very far with it!

**Pull request merged**
