### PR TITLE
allow all types, not just `view` to be resolved via namespace

### PR DESCRIPTION
**Pull request by stefanpenner**
- [ ] add tests (was having issues with the old ruby tooling, wont have time till after work to fix)

### CODE REVIEW

**Comment by stefanpenner** [comment]
@rwjblue / @bcardarella r?

**Comment by bcardarella** [comment]
@stefanpenner https://github.com/ember-cli/ember-resolver/blob/master/packages/ember-resolver/tests/core_test.js#L66-L112

ember-resolver can already look up any type in other namespaces. That specific line is intended for the alternate form of view lookups which I assumed was not necessary for other types based upon ember-resolvers existing test suite.

**Comment by stefanpenner** [comment]
@bcardarella i'll add my scenario as an example tonight. I was also quite surprised.

**Comment by bcardarella** [comment]
FWIW I've been using the namespace resolving with ember-validations and ember-cli-i18n without any issue

**Comment by rmachielse** [comment]
@stefanpenner @bcardarella I've added a new pull request fixing this (#80)

**Pull request closed without merging**
