### PR TITLE
fix(glimmer-wrapper): handle addon local lookup paths

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
rebases: https://github.com/ember-cli/ember-resolver/pull/297

### CODE REVIEW

**Comment by buschtoens** [comment]
_Bueno_.

Does it work fine?

I wish there were working tests for MU.

**Comment by NullVoxPopuli** [comment]
So far. I've broken a ton with some simultaneous octane upgrades. We'll see! Just clicking around the UI though appears to be fine.
It's just my tests are failing and leaking

**Comment by stefanpenner** [comment]
As module unification is no more, I believe this can be closed. If I am closing this in error please let me know why, and we can reopen.

**Pull request closed without merging**
