### PR TITLE
Change deprecated usages of Ember.create and Ember.keys to Object.create and Object.keys

### LINKED ISSUE #97: Change usages of `Ember.create` and `Ember.keys` to `Object.create` and `Object.keys`
This leads to a lot of deprecation noise when working with Ember 1.13.2.

Happy to submit a PR if this is legit.

### PR DESCRIPTION
**Pull request by akshayrawat**
Fixes #97 

**Tasks:**

* [x] 1. Rename `Ember.keys` to `Object.keys`.
* [x] 2. Rename `Ember.create` to `Object.create`.
* [ ] 3. Add polyfills for `Object.create` and `Object.keys`.

### CODE REVIEW

**Comment by akshayrawat** [comment]
cc @stefanpenner 

Not entirely sure if the generated `dist` needs to be commited.

**Comment by stefanpenner** [comment]
unfortunately for the time being this library still needs to support IE8. Please be sure to include the appropriate polyfils

**Comment by akshayrawat** [comment]
I thought that this library expected the polyfils to be present on the page, rather than providing it. 

Example: https://github.com/ember-cli/ember-resolver/blob/master/packages/ember-resolver/lib/core.js#L36

**Comment by stefanpenner** [comment]
In some future release maybe, but for the 1.x series of ember that would be a breaking change. That check is to ensure the right polyfil is use, if one is used at all.

**Comment by akshayrawat** [comment]
Got it. Since I'm new to this project, I've added a task list to the description above. 

1 & 2 are done I think. Can you give me pointers on 3. And 4 is a question.

**On 3:** Should we create a new file `ember-resolver/lib/polyfills.js` with polyfills for `Object.keys` and `Object.create`. Mainly copied from [here](https://github.com/es-shims/es5-shim/blob/master/es5-sham.js#L188). Or should it be brought it as a bower dependency?

Thanks for getting me started on this project.

**Comment by rwjblue** [comment]
@akshayrawat - Inlining here seems fine for now, we need to rework the build system to something more modern and when we do that we can swap to bower.

**Comment by akshayrawat** [comment]
@rwjblue Alright then this PR is all set. Let me know if I need to something else. Thanks.

**Comment by rwjblue** [comment]
I'm not seeing the polyfils here, did you forget to add them to `git`?

**Comment by stefanpenner** [comment]
Be sure that the polyfils don't smash the globals, this should remain an isolated change

**Comment by akshayrawat** [comment]
Added the polyfills.  Let me know.

**Comment by akshayrawat** [comment]
Not sure why the tests failed.

**Comment by stefanpenner** [comment]
superseded by: https://github.com/ember-cli/ember-resolver/pull/100

**Pull request closed without merging**
