### PR TITLE
fix(glimmer-wrapper): handle addon local lookup paths

### LINKED ISSUE #296: Local Lookup does not work for addons
Originally reported as https://github.com/emberjs/ember.js/issues/17395.

This code does not account for addons / paths that already have a `rootName`:

https://github.com/ember-cli/ember-resolver/blob/df3ef4e3b327b4cb70badafbe973b4c8c2aa7051/mu-trees/addon/resolvers/glimmer-wrapper/index.js#L96-L109

Specifically, L106 does not anticipate a `source` that looks like:

```
template:addon-local-lookup/src/ui/components/foo/template.hbs
```

### PR DESCRIPTION
**Pull request by buschtoens**
Fixes #296.
Non-RegExp alternative to #297.

⚠️ I have _not_ tested this in an app yet and there are _no_ tests for MU (that work).

Just wanted to put this up for discussion, so that we can merge this soon :D

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
I've tested this, and it works. however, as it's a fair bit behind, other things have broke (such as modifier not being a registered type).
@buschtoens can you rebase?

**Comment by buschtoens** [comment]
Sure. I'll push a rebase later today. And thanks for test driving this. :)

**Comment by NullVoxPopuli** [comment]
I have a rebase on #352 which I'm testing out now -- didn't work. however, I noticed I got confused by PR names, and I actually need to rebase this one: https://github.com/ember-cli/ember-resolver/pull/297

**Comment by stefanpenner** [comment]
As module unification is no more, I believe this can be closed. If I am closing this in error please let me know why, and we can reopen.

**Pull request closed without merging**
