### PR TITLE
Fix namespaced resolves for all types

### PR DESCRIPTION
**Pull request by rmachielse**
This pull request fixes namespaced lookups for all syntaxes, and not only for views:

- other@controller:post
- controller:other@post
- controller:post

I've added some test cases to support this.

This pull request replaces #80

### CODE REVIEW

**Comment by bcardarella** [comment]
@rwjblue I forget, are we allowing compiled `dist/` in PRs?

**Comment by rmachielse** [comment]
@bcardarella should I remove the `dist/` folder changes from the pr?

**Comment by bcardarella** [comment]
@rmachielse I don't recall. @rwjblue never responded

**Comment by rwjblue** [comment]
Nah, its ok.  I just hate bower :crying_cat_face:

**Comment by stefanpenner** [comment]
we will look at this soon, when we piece together the larger engine/namespace story. Im nervous about a piecemill approach without the broader picture.

**Comment by rmachielse** [comment]
Awesome, I am looking forward to it. However please note that this is actually a bugfix.

**Comment by stefanpenner** [comment]
cc @rwjblue 

@rmachielse can we get a rebase?

**Comment by rmachielse** [comment]
Sorry, was on holiday and forgot to get back to it. Thanks for merging!

**Pull request merged**
